 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: blip2_vicuna_instruct
  load_finetuned: False
  load_pretrained: True

  pretrained: "/public/qbwang/public/instruct_blip_vicuna7b/instruct_blip_vicuna7b_trimmed.pth" #"https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/InstructBLIP/instruct_blip_vicuna7b_trimmed.pth" #"/data/jiajian/haodongze/cache/lavis/instruct_blip_vicuna7b_trimmed.pth"
  finetuned: "" #"/data/jiajian/haodongze/phd_video_recognition/LAVIS/lavis/output/BLIP2_insruct/OKVQA/20230807214/checkpoint_best.pth"

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True

  # Q-Former
  num_query_token: 32

  # path to Vicuna checkpoint
  llm_model: "/public/qbwang/public/vicuna-7b" #"/data/jiajian/haodongze/huggingface/vicuna-7b-v1.1"

  # generation configs
  prompt: ""
#  prompt: "Question: {} Short answer:"

preprocess:
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 224
        eval:
          name: "blip_image_eval"
          image_size: 224
    text_processor:
      train:
        name: "blip_question"
      eval:
        name: "blip_question"
#    text_processor:
#        train:
#          name: "blip_caption"
#        eval:
#          name: "blip_caption"